spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: search-engine
  datasource:
    url: jdbc:postgresql://localhost:5432/searchData
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
opensearch:
  host: localhost
  port: 9200
  scheme: http